# Generated by git-weight's release workflow. Do not edit by hand.
class GitWeight < Formula
  desc "Find what is weighing down your Git repository"
  homepage "https://github.com/kris-hansen/git-weight"
  version "0.5.1"
  license "MIT"

  depends_on macos: :sonoma if OS.mac?

  on_macos do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.1/git-weight-darwin-arm64.tar.gz"
      sha256 "f283e598c862937b791d3853c2e32587518cac18b9c37c6daf25548c7ef29163"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.1/git-weight-darwin-amd64.tar.gz"
      sha256 "880f4d03dbf0b420729d48bc83921fe281accf8665f32b73632ee3ced2142942"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.1/git-weight-linux-arm64.tar.gz"
      sha256 "3f8f3cd69eb56679b049419f81aaea7e1bc1338ff165473be46f8f1ba1522cf7"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.1/git-weight-linux-amd64.tar.gz"
      sha256 "bfab5041eae20475bc59ae395e7d4b610e205c9b727a17bf398dbe134960a60a"
    end
  end

  def install
    bin.install "git-weight"
  end

  test do
    assert_equal "git-weight #{version}\n", shell_output("#{bin}/git-weight --version")
    system "git", "init", "-q", "fixture"
    report = JSON.parse(shell_output("#{bin}/git-weight summary --repo fixture --json"))
    assert_equal 0, report.fetch("objects").fetch("blob").fetch("count")
  end
end
