# Generated by git-weight's release workflow. Do not edit by hand.
class GitWeight < Formula
  desc "Find what is weighing down your Git repository"
  homepage "https://github.com/kris-hansen/git-weight"
  version "0.5.0"
  license "MIT"

  depends_on macos: :sonoma if OS.mac?

  on_macos do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.0/git-weight-darwin-arm64.tar.gz"
      sha256 "f14d9da7f50dc83803b63c5f0fa5afb11d6aaaf7e1157b4dadc6ef9bcea6e289"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.0/git-weight-darwin-amd64.tar.gz"
      sha256 "df4d2545e370d3c932ec8129ab6ec38ed76e0a883e6791dea07c66b024ba0b51"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.0/git-weight-linux-arm64.tar.gz"
      sha256 "416942abd454aa7f26d3c1aeb0aa2a0b445dd657f6b0c57f2e0e700a0a17d7e3"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.5.0/git-weight-linux-amd64.tar.gz"
      sha256 "7b8ca681a5df0c7e04fb41880e332b527729a28e728a8c6c8657ba409e35bdd5"
    end
  end

  def install
    bin.install "git-weight"
  end

  test do
    assert_equal "git-weight #{version}\n", shell_output("#{bin}/git-weight --version")
    system "git", "init", "-q", "fixture"
    report = JSON.parse(shell_output("#{bin}/git-weight summary --repo fixture --json"))
    assert_equal 0, report.fetch("objects").fetch("blob").fetch("count")
  end
end
