# Generated by git-weight's release workflow. Do not edit by hand.
class GitWeight < Formula
  desc "Find what is weighing down your Git repository"
  homepage "https://github.com/kris-hansen/git-weight"
  version "0.4.0"
  license "MIT"

  depends_on macos: :sonoma if OS.mac?

  on_macos do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.4.0/git-weight-darwin-arm64.tar.gz"
      sha256 "3aaeaa83eb621c1f83d2ba92f50d02912a93361cad616230f7de4a9db6f5225f"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.4.0/git-weight-darwin-amd64.tar.gz"
      sha256 "6803eb2d016d2b15ab30b6ce82d011c12f36cd7f8ed98c033ef9dbd3384b0968"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.4.0/git-weight-linux-arm64.tar.gz"
      sha256 "42b50366f6477bf1a72ed4e075a9e8c957d22adb85e1554651519cf35a3e4360"
    end
    on_intel do
      url "https://github.com/kris-hansen/git-weight/releases/download/v0.4.0/git-weight-linux-amd64.tar.gz"
      sha256 "e3ec55b20a51bb51cd83d81d1ab3b620f7dbac6def26b9edc1ad74769e6af365"
    end
  end

  def install
    bin.install "git-weight"
  end

  test do
    assert_equal "git-weight #{version}\n", shell_output("#{bin}/git-weight --version")
    system "git", "init", "-q", "fixture"
    report = JSON.parse(shell_output("#{bin}/git-weight summary --repo fixture --json"))
    assert_equal 0, report.fetch("objects").fetch("blob").fetch("count")
  end
end
